import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"], // Include the font weights you want
  subsets: ["latin"], // Use the Latin subset
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased flex`}>
        <Sidebar />
        <main className="flex-1 ">{children}</main> {/* Main content area */}
      </body>
    </html>
  );
}
