"use client";

// import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import { usePathname } from "next/navigation";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"], // Include the font weights you want
  subsets: ["latin"], // Use the Latin subset
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathmame = usePathname();

  const excludedPaths = ["/login", "/logout"];

  const showSidebar = !excludedPaths.includes(pathmame);
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased flex`}>
        {showSidebar && <Sidebar />}
        <main className="flex-1 ">{children}</main>
      </body>
    </html>
  );
}
